@host = http://localhost:3000/api

// ?fields=number,amount
// &filter[name]=Bob
// &filter[amount][$gte]=1200
// &include=customer,items
// &fields[customer]=name,number
// &fields[items]=name,price
// &page[number]=1
// &page[size]=10
// &sort[number]=1
// &sort[amount]=-1
###
GET {{host}}/v1/users?fields=username,email HTTP/1.1

###
POST {{host}}/v1/signup HTTP/1.1
Content-Type: application/json

{
  "username": "changjoo-park",
  "email": "pcjpcj2@gmail.com",
  "password": "1q2w3e4r"
}

###
POST {{host}}/v1/signin HTTP/1.1
Content-Type: application/json

{
  "email": "pcjpcj2@gmail.com",
  "password": "1q2w3e4r"
}


### 
GET {{host}}/v1/posts?include=author&fields[author]=username HTTP/1.1

###
POST {{host}}/v1/posts HTTP/1.1
Content-Type: application/json

{
  "authorId": "5b20f5d09ff13485cae6074a",
  "title": "Third Title",
  "body": "Lorem Ipsum123"
}
